# Generated by Django 4.2.2 on 2023-06-28 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=11)),
                ("user_type", models.CharField(default="10", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "user",},
        ),
    ]
