# Generated by Django 4.2.2 on 2023-06-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="profile", table="profile",),
        migrations.AlterModelTable(name="user", table="user",),
    ]
