# Generated by Django 4.2.2 on 2023-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_profile_table_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
