# Generated by Django 4.2.2 on 2023-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="name", field=models.CharField(max_length=500),
        ),
    ]
