# Generated by Django 4.2.2 on 2023-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="사공일", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="10", max_length=50),
        ),
        migrations.DeleteModel(name="Profile",),
    ]
